#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum State {
    InitialIdling,
    InitialLocking,
    InitialSetupSeparatorOpening,
    InitialSetupWaterPumping,
    InitialSetupSeparatorClosing,
    SoakWaterPumping,
    SoakWaterHeating,
    SoakWaterHeatedMixing,
    SoakWaterMixing,
    SoakWaterDraining,
    RinseWaterPumping,
    RinseWaterDraining,
    SeparatorOpening,
    SeparatorHolding,
    SeparatorClosing,
    Blending,
    PulpDraining,
    SetupSeparatorOpening,
    SetupWaterPumping,
    SetupSeparatorClosing,
    Idling,
    Locking,
}
